api/urls.py
from django.urls import path
from . import views
from django.conf.urls import include
from rest_framework.urlpatterns import format_suffix_patterns

apiurls = [
    path('data/', views.BookingList.as_view(), name='api-data'),
]

urlpatterns = [
    path('', include(apiurls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

urlpatterns = format_suffix_patterns(urlpatterns)

lugo/urls.py
from django.urls import path
from . import views
from lugo.models import Bookings
from django.urls import reverse



app_name= 'lugo'

urlpatterns = [
    path('', views.index, name='index'),
    path('book_ride/', views.BookingCreate.as_view(), name='book_ride'),
    path('book_ride/success/', views.success, name='success'),

]

project1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lugo/', include('lugo.urls')),
    path('api/', include('api.urls')),
]

api/models.py
from django.db import models

# Create your models here.

lugo/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Bookings(models.Model):
    PICKUP_CHOICES = [
        ('Hostel 1', 'Hostel 1'),
        ('Hostel 2', 'Hostel 2'),
        ('Hostel 3', 'Hostel 3'),
        ('Hostel 4', 'Hostel 4'),
        ('Hostel 5', 'Hostel 5'),
        ('Hostel 6', 'Hostel 6'),
        ('Hostel 7', 'Hostel 7'),
        ('MBH A', 'MBH A'),
        ('MBH B', 'MBH B'),
        ('MBH F', 'MBH F'),
        ('Mega Girls Hostel', 'Mega Girls Hostel'),
        ('IT Building', 'IT Building'),
    ]

    DROP_CHOICES = [
        ('JRC', 'Jalandhar Cantt(JRC)'),
        ('JUC', 'Jalandhar City(JUC)'),

    ]

    name = models.CharField(max_length=20)
    email_id = models.CharField(max_length=15)
    contact_no = models.CharField(max_length= 12)
    no_of_seats = models.IntegerField()
    bus_or_train_timings = models.CharField(max_length= 15)
    date_of_journey = models.DateField()
    pickup = models.CharField(max_length= 30, choices= PICKUP_CHOICES)
    drop = models.CharField(max_length= 30, choices= DROP_CHOICES)
    fare = models.IntegerField()
    suggestions = models.TextField(max_length=100, blank= True)

    def get_absolute_url(self):
        return 'success/'

    def __str__(self):
        return self.name + ' - ' + self.contact_no + ' - ' + str(self.no_of_seats) + ' - ' + self.bus_or_train_timings + ' - ' + str(self.date_of_journey) + ' - ' + self.pickup + ' - ' + self.drop + ' - ' + str(self.fare)

lugo/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Bookings



class BookingForm(forms.ModelForm):

    class Meta:
        model = Bookings
        fields = ['name', 'email_id', 'contact_no', 'no_of_seats', 'bus_or_train_timings', 'date_of_journey', 'pickup', 'drop', 'fare', 'suggestions']

api/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import BookingsSerializer
from lugo.models import Bookings


class BookingList(APIView):
    def get(self,request):
        booking1 = Bookings.objects.all()
        serializers = BookingsSerializer(booking1, many=True)
        return Response(serializers.data)

    def post(self, request):
        serializer = BookingsSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

lugo/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.views import generic
from django.views.generic import View
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from .forms import BookingForm


from .models import Bookings



def index(request):
    return render(request, 'lugo/index.html', {})

class BookingCreate(CreateView):
    model = Bookings
    fields = ['name', 'email_id', 'contact_no', 'no_of_seats', 'bus_or_train_timings', 'date_of_journey', 'pickup',
              'drop', 'fare', 'suggestions']

def success(request):
    return render(request, 'lugo/success.html', {})

lugo/templates/lugo/base.html
<!DOCTYPE HTML>
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Lugo - Travel Hands Free</title>
        {% load staticfiles %}
	<meta name="viewport" content="width=device-width, initial-scale=1">

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<link href="https://fonts.googleapis.com/css?family=Droid+Sans" rel="stylesheet">

	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'lugo/css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'lugo/css/icomoon.css' %}">
	<!-- Themify Icons-->
	<link rel="stylesheet" href="{% static 'lugo/css/themify-icons.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'lugo/css/bootstrap.css' %}">

	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{% static 'lugo/css/magnific-popup.css' %}">

	<!-- Owl Carousel  -->
	<link rel="stylesheet" href="{% static 'lugo/css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'lugo/css/owl.theme.default.min.css' %}">

	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'lugo/css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'lugo/js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'lugo/js/respond.min.js' %}"></script>
	<![endif]-->

	</head>
	<body>

	<div class="gtco-loader"></div>

	<div id="page">
	<nav class="gtco-nav" role="navigation">
		<div class="gtco-container">
			<div class="row">
				<div class="col-sm-2 col-xs-12">
					<div id="gtco-logo"><a href="{% url 'lugo:index' %}"><img src="{% static 'lugo/images/logo.PNG' %}" class="img-responsive" style="width: 60px; float: left; margin-right: 0px; position: relative; top: -12px;" />Lugo<em>.</em></a></div>
				</div>
				<div class="col-xs-10 text-right menu-1 main-nav">
					<ul>
						{% block navbar_elements %}
						<li class="active"><a href="{% url 'lugo:index' %}" data-nav-section="home">Home</a></li>

						<li><a href="#" data-nav-section="features">Features</a></li>
						<li><a href="#" data-nav-section="offers">Special Offers</a></li>
						<li><a href="#" data-nav-section="faq">FAQ</a></li>
						<li><a href="#" data-nav-section="contact">Contact</a></li>
						<li class="btn-cta"><a href="{% url 'lugo:book_ride' %}" class="external" title="Book your ride now"><span>Book your Ride</span></a></li>
                        {% endblock %}
					</ul>
				</div>
			</div>

		</div>
	</nav>
        {% block body %}
        {% endblock %}
    </div>
    <div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>

	<!-- jQuery -->
	<script src="{% static 'lugo/js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'lugo/js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'lugo/js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'lugo/js/jquery.waypoints.min.js' %}"></script>
	<!-- Carousel -->
	<script src="{% static 'lugo/js/owl.carousel.min.js' %}"></script>
	<!-- countTo -->
	<script src="{% static 'lugo/js/jquery.countTo.js' %}"></script>
	<!-- Magnific Popup -->
	<script src="{% static 'lugo/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'lugo/js/magnific-popup-options.js' %}"></script>
	<!-- Main -->
	<script src="{% static 'lugo/js/main.js' %}"></script>

	</body>
</html>

lugo/templates/lugo/bookings_form.html
{% extends 'lugo/base.html' %}

{% block navbar_elements %}
<!--<li><a href="{% url 'lugo:index' %}">Features</a></li>
<li><a href="{% url 'lugo:index' %}" data-nav-section="offers">Special Offers</a></li>
<li><a href="{% url 'lugo:index' %}" data-nav-section="faq">FAQ</a></li>
<li><a href="{% url 'lugo:index' %}" data-nav-section="contact">Contact</a></li>-->
<li class="btn btn-cta"><a href="{% url 'lugo:index' %}" class="external"><span>Home</span></a></li>
{% endblock %}

{% block body %}

<div class="container-fluid" style="margin-top: 140px;">

    <div class="row">
        <div class="col-sm-12 col-md-offset-3 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Book your Ride</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'lugo/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-4 col-sm-8">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

</div>

{% endblock %}

lugo/templates/lugo/form_template.html
{% for field in form %}
    <div class="form-group" >
        <div class="col-sm-offset-4 col-sm-8">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-4">{{ field.label_tag }}</label>
        <div class="col-sm-8">{{ field }}</div>
    </div>
{% endfor %}

lugo/templates/lugo/index.html
{% extends 'lugo/base.html' %}
{% load staticfiles %}
	{% block body %}
	<div id="gtco-header" data-section="home" class="gtco-cover header-fixed" role="banner" style="background-image:url({% static 'lugo/images/travel.jpg' %});">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 text-center">
					<div class="display-t">
						<div class="display-tc">
							<h1 class="animate-box" data-animate-effect="fadeIn">LUGO : Luggage Go</h1> <h3 class="animate-box" data-animate-effect="fadeIn"><a href="javascript:;" target="_blank">Travel hands free</a></h3>
							<h2 class="animate-box" data-animate-effect="fadeIn">We are the <a href="javascript:;">India</a>'s first Startup that deals with the Luggage and Goods of the Customers</h2>
							<h2 class="animate-box" data-animate-effect="fadeIn">*Currently functioning as a Ride Booking Service</h2>
							<p class="animate-box" data-animate-effect="fadeIn"><a href="{% url 'lugo:book_ride' %}" class="btn btn-primary btn-lg">Book your Ride</a></p>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	
	<div id="gtco-features" class="border-bottom" data-section="features">
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center gtco-heading">
					<h2>Features</h2>
					<br>
					<p>We make it easy to manage your luggage. Go Handsfree now!</p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-3 col-sm-6">
					<div class="feature-center">
						<span class="icon">
							<i class="ti-bag"></i>
						</span>
						<h3>Easier Luggage Management</h3>

					</div>
				</div>
				<div class="col-md-3 col-sm-6">
					<div class="feature-center">
						<span class="icon">
							<i class="ti-hand-open"></i>
						</span>
						<h3>Travel Hands Free</h3>

					</div>
				</div>
				<div class="col-md-3 col-sm-6">
					<div class="feature-center">
						<span class="icon">
							<i class="ti-location-pin"></i>
						</span>
						<h3>Door Step Service</h3>

					</div>
				</div>
				<div class="col-md-3 col-sm-6">
					<div class="feature-center">
						<span class="icon">
							<i class="ti-shield"></i>
						</span>
						<h3>Secured and Trust Worthy</h3>

					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 col-sm-6">
					<div class="feature-center">
						<span class="icon">
							<i class="ti-ticket"></i>
						</span>
						<h3>Special Offers Available</h3>

					</div>
				</div>
				<div class="col-md-4 col-sm-6">
					<div class="feature-center">
						<span class="icon">
							<i class="ti-wallet"></i>
						</span>
						<h3>Multiple Payment modes</h3>

					</div>
				</div>
				<div class="col-md-4 col-sm-6">
					<div class="feature-center">
						<span class="icon">
							<i class="ti-car"></i>
						</span>
						<h3>Pre-Book & Enjoy your Ride</h3>

					</div>
				</div>
			</div>
		</div>
	</div>


	<div class="gtco-section border-bottom" id="how-it-works" data-section="offers">
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-6">

					<div class="gtco-heading">
						<h2 class="gtco-left">Special Offers</h2>
						<h2 class="gtco-left">Ride & Save</h2>
						<p>Exclusive Discount for NITJ Students</p>
					</div>

					<div class="row">

						<div class="col-md-12">
							<div class="feature-left">
								<span class="icon">
									<i class="icon-check"></i>
								</span>
								<div class="feature-copy">
									<h3>Book 4-6 Seats at a time</h3>
									<p>and get <strong>12.5% Discount</strong></p>
								</div>
							</div>
						</div>
						<div class="col-md-12">
							<div class="feature-left">
								<span class="icon">
									<i class="icon-check"></i>
								</span>
								<div class="feature-copy">
									<h3>Book 7 or 8 Seats at a time</h3>
									<p>and get <strong>37.5% Discount</strong></p>
								</div>
							</div>
						</div>

					</div>
					<!--<div class="row">
						<div class="col-md-12">
							<p><a href="#" class="btn btn-primary btn-lg btn-block"><i class="icon-apple"></i> Buy This App on App Store</a></p>
						</div>
					</div>-->
				</div>
				<div class="col-md-6 animate-box" data-animate-effect="fadeInRight">
					<img src="{% static 'lugo/images/auto.jpg' %}"  class="img-responsive">
				</div>
			</div>
		</div>
	</div>

	

	<div class="gtco-section" id="gtco-faq" data-section="faq">
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center gtco-heading">
					<h2>Frequently Ask Questions</h2>
					<p>Dignissimos asperiores vitae velit veniam totam fuga molestias accusamus alias autem provident. Odit ab aliquam dolor eius.</p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">

					<div class="gtco-accordion">
						<div class="gtco-accordion-heading">
							<div class="icon"><i class="icon-cross"></i></div>
							<h3>What is Usable?</h3>
						</div>
						<div class="gtco-accordion-content">
							<div class="inner">
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
							</div>
						</div>
					</div>
					<div class="gtco-accordion">
						<div class="gtco-accordion-heading">
							<div class="icon"><i class="icon-cross"></i></div>
							<h3>I have technical problem, who do I email?</h3>
						</div>
						<div class="gtco-accordion-content">
							<div class="inner">
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
							</div>
						</div>
					</div>
					<div class="gtco-accordion">
						<div class="gtco-accordion-heading">
							<div class="icon"><i class="icon-cross"></i></div>
							<h3>How do I use Usable features?</h3>
						</div>
						<div class="gtco-accordion-content">
							<div class="inner">
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
							</div>
						</div>
					</div>

				</div>
				<div class="col-md-6">

					<div class="gtco-accordion">
						<div class="gtco-accordion-heading">
							<div class="icon"><i class="icon-cross"></i></div>
							<h3>What language are available?</h3>
						</div>
						<div class="gtco-accordion-content">
							<div class="inner">
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
							</div>
						</div>
					</div>
					<div class="gtco-accordion">
						<div class="gtco-accordion-heading">
							<div class="icon"><i class="icon-cross"></i></div>
							<h3>Can I have a username that is already taken?</h3>
						</div>
						<div class="gtco-accordion-content">
							<div class="inner">
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
							</div>
						</div>
					</div>
					<div class="gtco-accordion">
						<div class="gtco-accordion-heading">
							<div class="icon"><i class="icon-cross"></i></div>
							<h3>Is Usable free?</h3>
						</div>
						<div class="gtco-accordion-content">
							<div class="inner">
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>



	
	<div id="gtco-contact" data-section="contact" class="gtco-cover gtco-cover-xs" style="background-image:url({%static 'lugo/images/bg_mail2.jpg' %});">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row text-center">
				<div class="display-t">
					<div class="display-tc">
						<div class="col-md-12">
							<h3>Feel free to drop a mail at <a href="#"><strong>lugoservices@gmail.com</strong></a></h3>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	

	<footer id="gtco-footer" role="contentinfo">
		<div class="gtco-container">
			<div class="row row-pb-md">

				<div class="col-md-4">
					<div class="gtco-widget">
						<h3>About Us</h3>
						<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore eos molestias quod sint ipsum possimus temporibus officia iste perspiciatis consectetur in fugiat repudiandae cum. Totam cupiditate nostrum ut neque ab?</p>
					</div>
				</div>

				<div class="col-md-4 col-md-push-1">
					<div class="gtco-widget">
						<h3>Links</h3>
						<ul class="gtco-footer-links">
							<li><a href="#">Knowledge Base</a></li>
							<li><a href="#">Career</a></li>
							<li><a href="#">Press</a></li>
							<li><a href="#">Terms of services</a></li>
							<li><a href="#">Privacy Policy</a></li>
						</ul>
					</div>
				</div>

				<div class="col-md-4">
					<div class="gtco-widget">
						<h3>Get In Touch</h3>
						<ul class="gtco-quick-contact">
							<li><a href="#"><i class="icon-phone"></i> +91 7837401388, +91 7981404077</a></li>
							<li><a href="#"><i class="icon-mail2"></i> lugoservices@gmail.com</a></li>
							<li><a href="#"><i class="icon-chat"></i> Live Chat</a></li>
						</ul>
					</div>
				</div>

			</div>

			<div class="row copyright">
				<div class="col-md-12">
					<p class="pull-left">
						<small class="block">&copy; 2018. All Rights Reserved.</small>
						<small class="block">Developed by <a href="https://www.linkedin.com/in/kola-akshay-reddy-61890111b/" target="_blank">Akshay Kola</a></small>
					</p>
					<p class="pull-right">
						<ul class="gtco-social-icons pull-right">
							<li><a href="#"><i class="icon-twitter"></i></a></li>
							<li><a href="#"><i class="icon-facebook"></i></a></li>
							<li><a href="#"><i class="icon-linkedin"></i></a></li>
							<li><a href="#"><i class="icon-dribbble"></i></a></li>
						</ul>
					</p>
				</div>
			</div>

		</div>
	</footer>
	{% endblock %}

lugo/templates/lugo/success.html
{% extends 'lugo/base.html' %}
{% load staticfiles %}

{% block navbar_elements %}
<!--<li><a href="{% url 'lugo:index' %}">Features</a></li>
<li><a href="{% url 'lugo:index' %}" data-nav-section="offers">Special Offers</a></li>
<li><a href="{% url 'lugo:index' %}" data-nav-section="faq">FAQ</a></li>
<li><a href="{% url 'lugo:index' %}" data-nav-section="contact">Contact</a></li>-->
<li class="btn-cta"><a href="{% url 'lugo:book_ride' %}" class="external" title="Book your ride now"><span>Book another Ride</span></a></li>
{% endblock %}

{% block body %}
<div id= "success" class="container" style="margin-top: 88px;">
  <div class="jumbotron">
        <div class="feature-center">
			<span class="icon">
				<i class="ti-face-smile"></i>
			</span>
				<h2 style="color: #00860b;">Booking Successful!</h2>
                <a class="btn btn-success" href="{% url 'lugo:index' %}">Back to Home Page</a>

        </div>
    <p>In case of any change in plan, please inform at<br> <strong>+91 7837401388</strong> <br> <strong>+91 7981404077</strong></p>
  </div>
</div>

<span class="text-danger" style="margin-left: 105px;">You will receive an SMS or a phone call on the registered mobile number to confirm the booking. Please be available.</span>


{% endblock %}